### ISSUE TITLE
Forwarding messages to an e-mail address gives exception when using Mailgun

### ISSUE THREAD

**Issue by ArthurWeiden** [SpinaCMS/Spina-Pro#3]
We use the messages-feature for different parts in a website, and want to forward them to an e-mail address using Mailgun.
When the message should get forwarded we get an exception because the “from” parameter is missing: 
```Error performing ActionMailer::MailDeliveryJob from Async(default) in 206.15ms: Mailgun::ParameterError (Missing a from/sender, message should contain at least 1 from/sender)```

Are we missing a setting for the sender of the e-mail?

**Comment by Bramjetten** [comment]
You need to setup a from address in your `spina.rb` config:
```ruby
  # Mailers
  # ===============
  # In order to send emails, you need to set a default from address.
  # You can set an optional reply_to address as well.
  config.mailer_defaults.from = "no-reply@spinacms.com"
  # config.mailer_defaults.reply_to = "support@spinacms.com"
```

**Comment by ArthurWeiden** [comment]
Found it, thanks a lot!
